<a href="https://colab.research.google.com/github/sinku247/ms-py-colab/blob/main/Python_09_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy

#C언어로 개발된 파이썬에서 과학적 계산을 위한 핵심 라이브러리. 다차원 배열 객체와 배열과 함께 작동하는 도구들을 제공한다. 
#하지만 고수준의 데이터 분석기능을 제공하지는 않기 때문에 Numpy 배열과 함께 Pandas와 같은 도구를 함께 사용한다. 

In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
#zeros, ones, empty를 사용해 배열을 생성한다.
car = np. zeros((3,3))
print(car)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.empty((4,4))

array([[1.98649567e-316, 0.00000000e+000, 2.41907520e-312,
        2.37663529e-312],
       [2.22809558e-312, 2.46151512e-312, 6.79038654e-313,
        2.35541533e-312],
       [2.46151512e-312, 6.79038654e-313, 2.35541533e-312,
        6.79038654e-313],
       [2.14321575e-312, 2.22809558e-312, 2.14321575e-312,
        5.36094802e+199]])

In [12]:
#특정 범위의 변수를 생성 할 때 arrange(를 사용한다.)
print(np.arange(10))
print(np.arange(1,10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [16]:
# ndarray배열의 모양, 차수, 데이터 타입 확인해보기기
arr = np.array([[1,2,3,],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
#차원의 확인
arr.ndim

2

In [18]:
#데이터의 모양을 확인하는 방법
arr.shape

(2, 3)

In [19]:
#데이터 타입의 확인
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [23]:
# ndarray 배열의 타입 변환

arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)
print(arr_float.dtype)

int64
float64


In [27]:
# U1 = 유니코드형을 뜻함함
arr_str = np.array(['1','2','3','4'])
print(arr_str.dtype)
arr_int = arr_str.astype(np.int64)
print(arr_int.dtype)

<U1
int64


In [30]:
#배열의 연산
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1 + arr2)
print(arr1-arr2)
print(arr1*arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]


In [34]:
#더하기 곱하기
print(np.add(arr1,arr2))
print(np.multiply(arr1,arr2))


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [35]:
#ndarray 배열 슬라이스
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
# 종: 0,1 까지 #횡 1,2까지지
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


In [37]:
#
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0,2]

3

In [39]:
arr = np.array([[1,2,3],[4,5,6]])
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]]


In [43]:
arr[idx]


array([4, 5, 6])

In [51]:
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';', skiprows=1)

In [56]:
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [55]:
#기초 통계함수
#sum    합
#mean   평균
#std    표준편차
#var    분산  (std의 제곱곱)
#min    최소값
#max    최대값

print(redwine.sum())
print(redwine.sum(axis=0))
print(redwine.mean(axis=0))

152084.78194
[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]
[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [62]:
print(redwine[:,0].mean())

8.31963727329581


In [63]:
print(redwine.max)

<built-in method max of numpy.ndarray object at 0x7fa2d2d67f90>
